var A=document.getElementById("loopbool"),B=document.getElementById("tonecompcanv"),E=document.getElementById("toneoverlay"),da=document.getElementById("gridcanv"),F=document.getElementById("volsliderinp"),G=document.getElementById("repsinp"),H=document.getElementById("notedurinp"),I=document.getElementById("combinebool"),ea=document.getElementById("resetbt"),fa=document.getElementById("expbt"),ha=document.getElementById("impbt"),ia=document.getElementById("expcbt"),ja=document.getElementById("playbt"),
ka=[130.81,138.59,146.83,155.56,164.81,174.61,185,196,207.65,220,233.08,246.94,261.63,277.18,293.66,311.13,329.63,349.23,369.99,392,415.3,440,466.16,493.88,523.25,554.37,587.33,622.25,659.25,698.46,739.99,783.99,830.61,880,932.33,987.77],la="C C# D D# E F F# G G# A A# B".split(" "),J=.5,K=B.getContext("2d"),L=E.getContext("2d"),M=da.getContext("2d"),N=[],O=!1,P=!1,Q=200,R=80;R++;var S=32*(R+1),ma=R-1;I.checked=O;A.checked=!1;H.value=Q.toString();G.value=ma.toString();K.canvas.width=S;
M.canvas.width=S;na();J=Number(F.value)/100;isNaN(H.value)||isNaN(parseFloat(H.value))||(Q=parseInt(H.value));T();var U=0;L.fillStyle="#bbbbbb";L.fillRect(0,0,E.width,E.height);L.font="20px Arial";L.fillStyle="#222222";L.strokeStyle="#222222";L.lineWidth=2;for(var V=0;3>=V;V++){for(var W=0;11>=W;W++)L.beginPath(),L.moveTo(0,U+800*W/36),L.lineTo(S,U+800*W/36),L.stroke(),L.fillText(la[11-W],3,U+800*(W+1)/36-5);U=800/3*V}L.moveTo(32,0);L.lineTo(32,800);L.stroke();
function T(){var a=S,b=R+1,c=0;M.font="20px Arial";M.fillStyle="#bbbbbb";M.canvas.width=a;M.beginPath();M.strokeStyle="#bbbbbb";for(var d=0;d<=b;d++)1==d?(M.lineWidth=4,M.moveTo(a/b*d,0),M.lineTo(a/b*d,800),M.stroke(),M.lineWidth=2):(M.moveTo(a/b*d,0),M.lineTo(a/b*d,800),M.stroke());for(b=0;3>=b;b++){M.strokeStyle="#bbbbbb";for(d=0;11>=d;d++)M.beginPath(),0!=d&&(M.moveTo(0,c+800*d/36),M.lineTo(a,c+800*d/36),M.stroke()),M.closePath();3!=b&&(M.beginPath(),M.lineWidth=4,M.moveTo(0,c+9600/36),M.lineTo(a,
c+9600/36),M.stroke(),M.lineWidth=2,M.closePath());c=800/3*b}}function oa(a){if(isNaN(a))b=new AudioContext,c=b.createOscillator(),c.frequency.value=0;else{var b=new AudioContext,c=b.createOscillator();c.frequency.value=ka[a-1];c.type="square";vol=b.createGain();vol.gain.value=J;c.connect(vol).connect(b.destination)}c.start();return c}function pa(a){P=!0;qa(X(a.slice(0,a.length)))}
function qa(a){var b,c,d;ca(new ba(new k(function(h){switch(h.i){case 1:if(0==a.length){h.i=3;break}0==P&&(a=[]);b=1;c=a[0];if(1<a.length&&(O||0==c))for(;a[1]==c;)b++,a.shift();return 0!=a[0]?(d=oa(a[0]),g(h,new Promise(function(p){return setTimeout(p,Q*b)}),7)):g(h,new Promise(function(p){return setTimeout(p,Q*b)}),5);case 7:d.stop();case 5:a.shift();h.i=1;break;case 3:1==A.checked?pa(X(N)):P=!1,h.i=0}})))}
function Y(a,b){K.beginPath();K.fillRect(Math.round((a+1)*S/(R+1)),Math.round(800/36*(35-b)),Math.round(S/R),Math.round(800/36));K.stroke()}function ra(a,b){K.clearRect(Math.round((a+1)*S/(R+1)),Math.round(800/36*(35-b)),Math.round(S/R),Math.round(800/36))}function Z(){S=32*(R+1);B.width=S;var a=N;K.fillStyle="#bbbbbb";for(var b=0;b<=a.length;b++)0!=a[b]&&Y(b,a[b])}function X(a){for(;0==a[a.length-1];)a.pop();return a}
function na(){P=!1;isNaN(G.value)||isNaN(parseFloat(G.value))||(R=parseInt(G.value),N.length>R&&(N=N.slice(0,R)),Z(),T())}B.addEventListener("click",function(a){var b=B.getBoundingClientRect(),c=a.clientX-b.left;a=a.clientY-b.top;cellwidthx=S/(R+1);cellwidthy=800/36;cellx=Math.floor(c/cellwidthx);celly=36-Math.floor(a/cellwidthy)-1;a=cellx;c=celly;if(0!=a)if(--a,b=a-N.length,N.length<=a){for(var d=0;d<b;d++)N.push(0);N.push(c);Y(a,c)}else N[a]==c?(N[a]=0,ra(a,c)):(ra(a,N[a]),N[a]=c,Y(a,c))});
I.addEventListener("click",function(){O=I.checked});ea.addEventListener("click",function(){N=[];B.width=S});fa.addEventListener("click",function(){var a=X(N),b=A.checked?1:0,c=I.checked?1:0,d=0;N.length<R&&(d=N.length);a="-"+d.toString()+","+Q.toString()+","+b.toString()+","+c.toString()+"+"+a.toString()+"-";a=a.replace(",NaN","");prompt("Copy the following string for saving/sharing:",a)});
ha.addEventListener("click",function(){var a=prompt("Please enter your exported data:","");if(""==a)N=[],B.width=S;else if(null!=a&&"-"==a[0]&&"-"==a[a.length-1]){a=a.substr(1,a.length-2);var b=a.split("+")[0].split(",");a=a.split("+")[1].split(",");if(a.length>b[0])alert("The data is not formatted correctly. Sorry.");else{"1"==b[2]?A.checked=!0:"0"==b[2]&&(A.checked=!1);"1"==b[3]?O=I.checked=!0:"0"==b[3]&&(O=I.checked=!1);R=Number(b[0]);G.value=R.toString();Q=Number(b[1]);H.value=Q.toString();b=
a.length;for(var c=0;c<=b;c++)a[c]=Number(a[c]),(36<a[c]||0>a[c])&&alert("The data is not formatted correctly. Sorry.");N=a;Z();T()}}});ia.addEventListener("click",function(){for(var a=N.slice(),b="";0!=a.length;){var c=1,d=a[0];if(1<a.length&&(O||0==d))for(;a[1]==d;)c++,a.shift();c*=Q;b=0==d?b+("  delay("+c.toString()+");\n"):b+("  tone(buzzerpin,"+Math.round(ka[d]).toString()+","+c.toString()+");\n");a.shift()}alert("void playTune(){\n  int buzzerpin=0;\n"+b+"}")});
ja.addEventListener("click",function(){0==P?pa(N):P=!1});F.addEventListener("click",function(){J=Number(F.value)/100});H.addEventListener("change",function(){isNaN(H.value)||isNaN(parseFloat(H.value))||(Q=parseInt(H.value))});G.addEventListener("change",function(){na();Z()});
